apiVersion: v1
kind: Secret
metadata:
    name: statping-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    statping.yaml: ENC[AES256_GCM,data:T4Emdan6H4h6uUlqpy+xA6NYKhZ883tJkzTYceLJRT03jSYBE1x4TmM4ca6iweh9RcPIPYjfolCHOMfXvywypBEfexXxZ4cnWR94oxkRV7TO3HCVrVBaeJgxp2dUUT8o3Bm7tkRtmDBzVL8NejrHOPlr3C1Qo56lNtP0iThtsQOcTKZ3ytgS+NH4D5N+8tcTkRHcYkJj04h/AhWbs/twAILl7XEj2TDds8/xo/aRhCcwxbvxuGMLg/w=,iv:EsILFnZ9wD2TWMLlVZFER4LEM+vJt3pEGVhvCBrMAfA=,tag:R0XBe623iHNRPRcKXznAOA==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:3mOJ2ALsVSPkyRWefovN7c2a863nkydkkxgkIlyAoJCSOclDqh02rVZIbOVI2LWrgqPb7cVjDq6hCinJ1/HgN7btIVWVDhbFKuZsc3bm6BbavkT2yw5c0Z2J,iv:maGCVfaKmOwWby0lD7zYia3zDDKEm0pqQj73vNSUdVs=,tag:5w/RICWQJBa8oLBqvNlpjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-31T01:53:51Z'
    mac: ENC[AES256_GCM,data:ME7S3uLNeMJLbBBlcrv11WkyVA1Bd86DMFXj2boWmn33pSGuwn9LE6Klyi/uuST0grKBIuWQC+t43Mam8ME+gXBv2w5e71TorVpz++hpNynvqgA9lEv20sGt86a6u8+sceeR5+3+G7TnIdcx7s/RnJN+W1sxvpyLWCJJx8fCtok=,iv:mr2P/mjS2qEIaHQqulzAMrvcj0TWz4CRZhmd0NaHL3E=,tag:aOo0mvb9fmLCBV/KGr1Plw==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
