apiVersion: v1
kind: Secret
metadata:
    name: maddy-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    maddy.yaml: ENC[AES256_GCM,data:5NBFexum51pV0oBuH7oEAoOoUqb7UUG4JCqxLXEtBmRbG3gFl7gmNKIxcCoYEFTN/Ud9pXBgCjUJKdaxIjMl2gzn+O30DQ8HrKOXrwWqrMS2L+gMRKEAIWmCUBOW/wC4kx2UdkPFWaIiIuOqlY2x2z2OwxJ/HMj9Om0bEyEQPYDu/tsqo3+m+bX/uSKHGRRVaiZ1KCmH/MuUBeREmoVFGT1C8wcARj9tRavLTCgGr6DA7VOINLDuHr+22jFfjeY9aW41WINL9ogYVtruXCTDQUJX6L/OeGynuWQVNFQ/pEPKRWU/51TpATA382qADUWvpXLB/OWrXsK9o9i+WFiiEMkzHYWqVMq2ROaQtU6ktP+w2ySrLqm235jvOcKl/V5nKa9FISXAZxBS9/D1lvZW+pZEBDTVmDuDn4jBYYg+BvJ6gYFgZZA9cnk11REeXIEm4PH847QLSnQP6bwwSbXs2KagYN0BQWxCTkOmvcpvXOO84DGRHJADg+kYe7pJuqyVA5tImzRPKxVsQ43vexnLq7N02nVawYPcYVO8FXJ0yA+HYbCKwL4os0wHyCaRy3e089LOdw5pRQM/UY8VNehAlVP/ggWrA/yGjCvrQO9yDOxZQe0AJF/Jxk/k+Y5li1xZPkkaEOXyj5jeFnCz3I8zvaGRWTsyo+jP8T4vWqeex0HeOqRw2n1MHQLYksdZK5t3SpblW7T6CJtIBXmOXOMxcUQrhSIciheCDa6PvUZxDHn6a0Z/vhk2Ef3+D0BkzwIpjXEzXfKnqP3BG7ldCOJ9qFN9hcInli2Vvn9fdK5wFqFSSS4TuQ4UCWAZHfSRdHruym5sNvHlYHm6Bb/ARbXcuGc4pECbnGWBOHUp5hq+SSoWxycFtMAkf4M4WZnZeJRjivDhnZyZw7+VKojallMWBM16fBFEM/D9YE7ZcDM+fBxjrq8MNLkEt4AvY4ccEbRjADU1Eu2eHfwYfW1wbRaElKc+KtTFUwwkEzeTANekqW/YLYAc/Z3T6saN5HSqFZGNdpRQWKE/6fwkftSuk+98pVCnXtUlpPZwk280mU4uSiiz0yyTrXhUnr3xjDB6cf0hwgllMQRtYzOYsXqd7doRPL7vj/zohzZlpKSETc0Hlqhirw4G9uXgr5k2E6JFEddkqSbiYO2qhPc6/7a5pwAMOHR8F8aWrnKaEe4syBCR8RiTYmq2Z+0ys04qb+N0258bNjxyIyc8yQ==,iv:n3KMsCQwYrWRk/mIax80JT1/VSKrz6b7nfG0T+UMIy4=,tag:Cz9NebC+TopxDCFnNXLwlg==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:OxZ1Jj5UbnpavYtpEk32R3Tu9FogeQsyypgk4ura6LKlG8rMWIlEzWKwKTtOudkxaavcm0Rd+4v1Q6LtImLB4D+/YEY4i0GbHR/ItA==,iv:xTlrtxJPxfSfwKvjLREfGIKJ6U5HPgMo4/sEPCl8ZUs=,tag:KnJv+oTnXsK/aa1LcVOCPg==,type:str]
    foo:
        create accounts:
            - ENC[AES256_GCM,data:p1q8zWZj+2HQNg417kWk06ifKUHl+fbdR3wWC1Ys7MnqeB4+E8XVwY5YezyPRh4u2ugM6ECR7oNJRLBRo2Xj2VaBwOqmPhqpPkzkdm0TB5peSX/h4zusd82ZgViw4BJO,iv:KyMFHLRdFk7Koav9v61eZYK93w6ivOQyqvqlh8bJYAw=,tag:BlGBc2Gxu1ycxFPHf0+ksw==,type:str]
            - ENC[AES256_GCM,data:cjjFfKYcPODRdDGgQITLtCGWbh1rMeKHBpXiLl01x3kZ1o3YmENFoCMhkAyocau5F/fzNcoWMsKFwaqapspUpK7HvEbutx6zOzxaK8rsO4rKRPDD,iv:ugw4e8fzgSQGUjaBOnoWUBq4flKz+IJsepVhoktV3+U=,tag:1b21K250ElkHoOfTNRuAeg==,type:str]
            - null
            - ENC[AES256_GCM,data:m1ovPt3V+slcG3ZNFUczs5V56N97O4yqm3IDGgyHTknLD4Abv0sF4twXbBXLACq/7un2no6hHFbu2jW+6tOIvHEe2RW6NHYVkP8iIDr9VfuozoqV158UjnmWzyLnSltzJXEzODINeZLth0nCGR39Tcgn5zwjO6skS0Kl/Zz1CJqi1pnFo/RM23VmeNcJwGFqukKfxcHeF2DSPEKCS9+G+oF5,iv:ehYAhr2RFIWEIbR6PhzPGfSms3F1AHxlwOXnw4PoHao=,tag:Na1zD0XtY37YvomQLrWVCw==,type:str]
            - ENC[AES256_GCM,data:EeX1B2Fi7NtP4MMLNoBrLypmOG+3mSyDnKTO+NIYTN9Ck67/nFNH4z3DnDcIJgjCEiH4cScXhVGN1T7xQO6+HA40byg/1imOelZvvQ8vIiUl5zQyjMuXCtXVhtbXOUK6wAbswkd9MZfiHlLGls7Hxgldth/A0hvzmZfMtv7M+s3N9qvTWZW40n0pwmAzczwWY7vTEWRERtSpfvBj,iv:kPcOdpcaf+W9thG2iTd1Ir9IN3QLSCvliH5jE06YXFs=,tag:CiIpvt8kyA5p9+TD92opPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-30T13:25:02Z"
    mac: ENC[AES256_GCM,data:FJ+WHoDxTVipwLT5Qm+jjzgcr0RhpCK3xDf/eqMELypBp1K09GSF7u77CibKpx99sZGDh8H8+xG9aRDBs/TTOTCRiOL1GqWHvrI9YzjF8zeXNx0Hf+OVuhnXCGc1qfy0lEWdy8qWrcwpNffLc4sOR99p2xMdkplatrx1sr32Hbk=,iv:U/reduS2pau3qSnrtk3Sm6fdJAq6sHzOmKA3WxsCfkg=,tag:ZO5NrS0FZIr95udabX+t7A==,type:str]
    pgp:
        - created_at: "2021-02-06T22:26:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
