apiVersion: v1
kind: Secret
metadata:
    name: maddy-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    maddy.yaml: ENC[AES256_GCM,data:7XtohDfqlERdg/9aL+Smjht6jfopqhmHEyX3Ve7A/F2UfF2CJPKqh4S7LPB7ZqgZR0g44FViVEoZxD4E2ec6g9R6uN4YlWXWbLLHJ5hgWBr0NUgwhRtypsHdMRmzucc6L9u67/s8MgtBJkJc482+xLXb2xZzOHYW5KXpvGAA10CJoeW6S/ldMm1hqsS8L0iv11676g==,iv:AWF9D3UMrg+RcWNtfi9o5GCEJ9kJo9Smkat7iDRQZS8=,tag:u5+a1Gej5thC2fM8M6ln3A==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:OxZ1Jj5UbnpavYtpEk32R3Tu9FogeQsyypgk4ura6LKlG8rMWIlEzWKwKTtOudkxaavcm0Rd+4v1Q6LtImLB4D+/YEY4i0GbHR/ItA==,iv:xTlrtxJPxfSfwKvjLREfGIKJ6U5HPgMo4/sEPCl8ZUs=,tag:KnJv+oTnXsK/aa1LcVOCPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-24T00:12:25Z"
    mac: ENC[AES256_GCM,data:ddZZ6xWuN8M82JF9Tgllr/FYXncs1IX0V56QNv9VUZTpwDLSyawpOtIwnZpV+1i+YKesgx1zU1Y/2QgktGoPlt3QW3w9JXC6lCGisoL0X+yNv8xgwMlrwbKrtEjXxWZZ1dEmNSkiS/cMAjZ55XxkSnO/V9PZBAmZL/b28+i4mR4=,iv:sLROBdmC3/exqr/oxVn8mkNitPM3YDOHeQyiSAt3sCQ=,tag:laoeQURh5sszYHYqP/Yv7w==,type:str]
    pgp:
        - created_at: "2021-02-06T22:26:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
