apiVersion: v1
kind: Secret
metadata:
    name: maddy-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    maddy.yaml: ENC[AES256_GCM,data:l/tE6L8nw/ch2ZRYodUIynrbvmuyGKaIMFjgEAsfv9lnzfR/iK6+ZABmdUQAjwfR4w8AbYN88V95Qgbnju6aUSIVsmkPTL563O3jE02mxhn0IrJrX9skS+bRJmzUdPRIoTalA8lqqS1n8GE2x5aTrEE/0sq83Kh//W9Xo2J8uExWkmEiHLq5moXUIs19fqQMmqhDyGuh2sRxIgUYBHvfZapQ56lHNYxuBZ+PdbdjZEKigXPZqlnnpPuMbwtB4H5iFO/gLKYGiClfoiT+0fQND+gesKY4QtYMiRGaQ5QlmoNVyZ8E+vEnFnEu0Q8dJ4K7YYcNMXMIjx/Sjl0vQUjVekqZko4PbSI/WIaczAKjnw9XoI7uMEI9sJKrvbdjGkm1Kn27uBbg40kO6z0mz2Mj5hcek/MYmLpoIk+xed9g6cDQcwLyOcd8/yk4rq+qqgsQ6FyiL5tXl2UV8VnT6cdgDJnyIGfuEyhzoM1pCTASyM42/jAhVvUjthAYBGWdm1PBS44/khWZdOTV4/xB0XSJvGcxtzOhZ2VknYaJAjjJoZWiOCAHJ0hWH1iWwXiO7t1+xADRIuMMDDzOZ8qKGolBjcVwDSa6TjMRFnwOJZ2FtaIQ2r8YGO9KDijzk1UMJcgjDdBsXt9ymXELJF+vRVHIry4Xj9cltessCbRTUEUbyLnGEJRR80AZU7unbeE1XKGmDO7To/7aAYoD4EFTMwCtCTbJTOZFruQS/u/w3+vlvM7rYQCF9fiMUdBlR7BkpD429v1WipxjfapXQffAcDCb3617ZjCr/aBex4szymuuJp0p46ldyWPLoYoq4G7R7hcNTRxB+wmVRSJ2GRjsfzHd4sMhSM+wx2eGUahZR6QYRDwjIMFXUsdj20TkjaiJPrBLJaEV+KgYumAvYBxZuZIeUzaPofHNecBBks7GPEMfp6xFe/4N4S1eojjPSvrrPrwzKP0QdoXyr+gSn5qanjL6f+jfyQTrw6h71xwd90qIc1PMRKEZPh6T6IlLCwrmctds5upQfdYgcUcFJ1k5VcMaIgBWDpOska5i4cosbUJXwQXrqodzh4HXW4XEzoeg2L/Cqu/RGMNx96W9KyPenEnAssurrPDvQF9VnW7WT3ZQlkYz4kDi5Ud4V9MJIVFTP785hh6eBt8FSRPoO3lPsob/mWwbpCuiko5bMN9bGtvwS8SuI/94Vp2UQ/NZGU0ILCbGVDby5Mq7s4vB+wam8NAjkHYCeqbnxEbrVMMmJ7i6DjnbmrOm8jD6dF3c/eFVybWh+M0xEwIVunAWtDvv8+4mzZx0bG+aGysqZPci,iv:LTkXgwXO2zUs/AzFaYMDXW+dFhzctZgJJTvn9yA8f7o=,tag:GBSFzX5UyhQ17vcv+cA6Lg==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:OxZ1Jj5UbnpavYtpEk32R3Tu9FogeQsyypgk4ura6LKlG8rMWIlEzWKwKTtOudkxaavcm0Rd+4v1Q6LtImLB4D+/YEY4i0GbHR/ItA==,iv:xTlrtxJPxfSfwKvjLREfGIKJ6U5HPgMo4/sEPCl8ZUs=,tag:KnJv+oTnXsK/aa1LcVOCPg==,type:str]
    foo: ENC[AES256_GCM,data:5vXAv/xJwBPLvHQVu9eEMJZOZB7/NDn7nNEPAWXfEhfk9GOOsfNtwafm48RFN7giSmi/lV7jH5jmo+RZhqe1GWcUOIPevYI+dFnGdJ973znvo5ctrp7q9fkpeESqHVU/FgYV3JVfPwoMNJcc0bk8QpX5QWsj4OLG9P8fen69wty3k+UYvdc/d9gFB+HCZBLTKAvTeX/xDnB3ECMGkGcSOSHyOhsJGm39X8UJ9c5RdoyiQQJRYC7bXmagc/OVGDaGd1I9aWGGpDr+aUtpkxWFludDPDY2omGFBrchRyLxUql/uoy0hsDrquMyD8V9w0h3jc6tL+VR8k+AWcVtmN4jAAlTMkngZyacgf1SWkIOEjmGKSFgS5prFNMomYAq+VAua1BqYA58nBaE18g61FxDmMUVbablDJ0I0M1dj2EoSIbMUnbksABl4cDa7olIrWWFn5rr9y4i/BRfcBntTbETRyVRS4Vh7ShfTMNuUf+7D0zIE+EA6IsSnCzia8u2NmbqV1zz7CKl1XVgHurY9DYRG9sOd28oahecPhxFmVFwVOESQxgrJp8Ym6mLYT/f+bvhU53Ogef+mOSdZtuyOp1chVNLFZDwT8/J/wJEdwZj4N4TPIfqnXQQRC8F0YirZIwt3ShdoDrL39PDtke8DpQdv2j+xKavi0Xx0E7Y3ti3RMwf3M9MoFh8WQRdvACt0Wfc10rLOWgRgQGI9/9UGgcumaow9PaQU4G51I4=,iv:lw5ZjFJSmOCrAdXKMwHEUfo0HEtnNjwQR6jl4nG3I4k=,tag:3Zbq5ejWQaxnlt1kHevPYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-30T13:59:22Z"
    mac: ENC[AES256_GCM,data:fT+TDY4fTX5GfRw70iycs0kThIlQNTyOR0yCzF5SeVBLzuMjpJwDylQ/Mg65GuYZ4J4QAW/X3Cl7MAWdrxPH9iyFDFDoSDdZVWlTFtMQ9UimRQiOIaR0FOd4gNfoOIId9Jh69YL6QORSLx1DfQRF2y2dCV/3+dSNEYBTYtNs5vQ=,iv:7S6fFUJXTA8cJDaYP6tUk2m8GIe/yzjyCrLDqJxO1RU=,tag:o6FlcKfmoaPH2sxRBMv51A==,type:str]
    pgp:
        - created_at: "2021-02-06T22:26:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
