apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mailserver
spec:
  interval: 5m
  chart:
    spec:
      chart: mail
      version: v3.3.0
      sourceRef:
        kind: HelmRepository
        name: mail
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: boky/postfix
      tag: v3.3.0 # Override version from Chart's AppVersion
    
    service:
      port: 25

    persistence:
      enabled: false

    config:
      general:
        TZ: Europe/Berlin
        ALLOW_EMPTY_SENDER_DOMAINS: "true"
        # ALLOWED_SENDER_DOMAINS: ${CLUSTER_DOMAIN}
        # RELAYHOST: secret
        # RELAYHOST_USERNAME: secret
        # RELAYHOST_PASSWORD: secret
  valuesFrom:
  - kind: Secret
    name: mail-helm-values
    optional: false
