apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
spec:
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - "$(GLOBAL_EXTERNAL_SUBNET_PREFIX).128-$(GLOBAL_EXTERNAL_SUBNET_PREFIX).192"
