apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: system-security
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 5m
  values:
    image:
      name: ghcr.io/goauthentik/server
      tag: 2021.5.2
      pullPolicy: IfNotPresent

    ingress:
      enabled: true

      hosts:
      - host: authentik.pub.${CLUSTER_DOMAIN}
        paths:
        - path: /

      tls:
      - secretName: tls.authentik
        hosts:
        - authentik.pub.${CLUSTER_DOMAIN}

    authentik:
      #secret_key: #in cret
      log_level: debug

      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s

      postgresql:
        host: '{{ .Release.Name }}-db-zalando-postgres-cluster-postgres'
        name: postgres
        user: postgres
        # password: #in cret
      redis:
        host: '{{ .Release.Name }}-redis-master'
        # password: #in cret

    postgresql:
      enabled: false

    redis:
      enabled: true
      auth:
        enabled: true
        # password: #in cret
  
  valuesFrom:
  - kind: Secret
    name: "authentik"
    valuesKey: values.yaml
    optional: false