apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.dexidp.io
      chart: dex
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      interval: 5m
  #See https://github.com/dexidp/helm-charts/blob/master/charts/dex/values.yaml
  values:
    image:
      repository: ghcr.io/dexidp/dex
      tag: v2.28.1
    env:
      KUBERNETES_POD_NAMESPACE: kube-system
    ingress:
      enabled: true

      hosts:
      - host: oidc.${CLUSTER_DOMAIN}
        paths:
        - pathType: Prefix
          path: /
      tls:
      - hosts:
        - oidc.${CLUSTER_DOMAIN}

  valuesFrom:
  - kind: Secret
    name: "dex-config"
    valuesKey: config.yaml
    optional: false