apiVersion: v1
kind: Secret
metadata:
    name: drone-secret
#create with openssl rand -hex 16 | base64
data:
    DRONE_RPC_SECRET: ENC[AES256_GCM,data:cJcMK/O5jJbpdRrWHqb9/LptT/dhBnxiEEZBbEnhiPcsEZSazoGw7ZPB81k=,iv:TL6Jwf8yWUp31lTXT4QZl/TYcLQWA6/mhQAWXB3t6+g=,tag:xDIXdQD/ltKCuMNjLzcReQ==,type:str]
stringData:
    DRONE_GITEA_CLIENT_ID: ENC[AES256_GCM,data:CTj/gS4FW1n6xBOxix9NAkVQnSHD1EeKIsYpheSiTA3muS4L,iv:GxPYK69qy+ERbPesNZMPCwLpfgKcxrb9Wzr37VqHPj4=,tag:wsRUSZy3krnLyj4hI78rNg==,type:str]
    DRONE_GITEA_CLIENT_SECRET: ENC[AES256_GCM,data:mfnuL8Td3IMWUoZN48fGJgY2jMU1IZywUsdsoD0rzBJa95fhe9GPTLeKB+c=,iv:42qKBjOGmQ1a8uG/BFfyy0tndje6tdFus3u4zqglvY4=,tag:z9QWKI7+m3bZ/qZARHvy4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-06T22:26:03Z'
    mac: ENC[AES256_GCM,data:mh8ivRjqV5RWBmPGgOapCWWV46oYNDLvnSuBIfn1lARvkvYDhG2Dr7Ju8w9jVF4s9ITOONBubwiRfe2bXQ1WAw/eT006GqqZO/bUgLKTZR+biAmg9aX+2wH9V1IdxEiS7DeMqhe2wg6N8S7v7EmS7Rpk2yr7n3zSwlfHBYSUhj8=,iv:Ug5Lx49o6ilGz3bMvIpZ3Y/+Ei+YRpVAhBa7bs3+Qhw=,tag:DRuWMi/qF5IpbEZ7EGCWRw==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
