apiVersion: v1
kind: Secret
metadata:
    name: heketi-admin-secret
    namespace: kube-system
type: kubernetes.io/glusterfs
#create with echo -n "admin" | base64
data:
    user: ENC[AES256_GCM,data:p5CZ/f8PlRc=,iv:CVzXNAHJirt6gZd1U8o+2uLtnq0yiBOQVqQqMi/jn+g=,tag:/TZwwtpHms+gbAiAWKtpzg==,type:str]
    #ENC[AES256_GCM,data:teswCc5LURB1n4y21e1/gcEdTrjFA52h6g0iKXHOcYA0QUHLVygMtmg=,iv:5oKGL95ceZNtA1u59sOGTitpXHYSL9SbG9AWskYs0fk=,tag:bdOPKePGCUArAHxV0FiA7g==,type:comment]
    key: ENC[AES256_GCM,data:qvKE/lVucOyRGQMTNxZhcpKShFatJLSqPZZSsR1aErBA2iRKeOKLy2SUCaI=,iv:B4+OFi2oB0kfFUMpWVaDCe9eOAAVE2E8nQkrlHiGSTg=,tag:V5Pgqcb/l+e2NHFNubyTSA==,type:str]
    #ENC[AES256_GCM,data:PQtgu8KwL41d,iv:nVdHm9eHLvZLDeGsWot6Yd0VgAZ+G/LIetoWXiNMHUs=,tag:RTC6mycIjfBAa9nzYN/PpA==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-06T22:31:20Z'
    mac: ENC[AES256_GCM,data:SHdumwuB65MkD/QIOl3VFu2Omu8h7paPwgX8qA6uN1VcMLd/3uSq7OmFtWqVwCWrGoELxjL7lOU/B7sLpirsJjMvERHIlqN3VC9hJm0HinHl0eKoBXZxNeK8rMi9NAMEus8p7dQtGbrCBoo+49Wu32UY1e+JExnw+JO+7pCMAK4=,iv:/oU97ApydRO+Ioh0BQotm2DTa3xIOQZpyVXEqCNy3YI=,tag:aAYuyeu24bUPGqPPjkd2iw==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:31:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/+OJYvhBql+vbzjT37DBZKckGbgXAYEcKrasOoGkkVAZI+
            splOfAjpR81qunXg/rtzsuQwaGvKbNfK9bKYcVSpppIeoBueVNrdzA5Iy8iZsm4X
            qcoh839H618vgzqTEG0QPMobVqFzGzxKtI0S74H0pnXM+bQR/asuV95P/q74ZpiZ
            rXfcSmFK/f99Xf5qA0ztV2HHlASrzIetus0xblbcmJbF7Yw+PxI7qovpu/uQlU4w
            34jTAhmP8jrzjAfMYBh7T6BKDgNAlOyzaFE6fdYw/Ymbh+LQlRz+Rbthpo9AXYFe
            YqlXZefE2nwshB1mPXKLvYXKxfUvaFnTPPUbv/3zIsY1DZqkcNCPQumoooSf1v5l
            esSEhoT9iuOyPW0eh4Fee8E6qvlXMsGztyFrHrfUlimDhataqbnEQWM075OcdhcV
            oObBKxyiE7k45Q2pOn+diwQI9lDaYv8spcnAdfw28BUeNIR2TCBNvYVmMJsbnIIm
            E7WgZi0acl1bcRXseY1eqvXHs1LPh2/lv+cgYchuYXUizKuCUunKb54uUEM1jKHv
            TsuQyMMZq8ND617C7urPOeIlaWNcKQBxtJ/OAg08FLAHbGfGqpdzSAQXoO4h55mK
            Kox1JAjpnUgijS3oxsb9Y93/rv/Qqwmz2OLYK/K8+OdmeVfvYMX4mpOdn2zmyVDS
            XgHiuJAgTmvzEiUEjW8oQzOareHZWN6D+Nev5VbYlrKWljdy9YAqT6T//FDeYiPY
            byatBbmgQ05f9TFg9D2bqhS9VujnDkhAN6aIUKzb+vYruEyOmJ04vDeNaVEdQos=
            =LxaM
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
