apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metal
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 60m
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/bitnami/charts/tree/master/bitnami/metallb/
  values:
    controller:
      image:
        #bitnami version only has x86_64
        repository: metallb/controller
        tag: main
    speaker:
      image:
        #bitnami version only has x86_64
        repository: metallb/speaker
        tag: main
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        #- 192.168.1.128-192.168.1.191
  valuesFrom:
  - kind: ConfigMap
    name: app-global-settings
    valuesKey: LB_RANGE
    targetPath: configInline.address-pools[0].addresses[0]
