apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-kubernetes-kube-system
  namespace: kube-system
spec:
  storageClassName: nfs-kubernetes-kube-system
  capacity:
    storage: 18T
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas.home.angelnu.com
    path: "/volume1/kubernetes"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-kubernetes
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-kubernetes-kube-system
  resources:
    requests:
      storage: 10T


---
