apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-helm-values
stringData:
    nextcloud.yaml: ENC[AES256_GCM,data:nkoY0CZPUaVA/AroQ/mhQNlVGPBK5V5Ub6b8+t+gwTDPW9Igcc9EbyP5yXGgpPsFtE6IXKHsRL6riD744eqWSJC1r8sqHV1a+bPGte/KCqle6sV9b1hnLAgqLOxD1Z1A3K2yMu/kKa5x7ZEVgh11ykCqEg==,iv:a8UAQRXs53Z2D1Vm83pZ8rZ43XfmRLU4JtCby5O1F6c=,tag:oMJgftFDw+2htVVEqR/C3w==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:gjsZKi2ugUFqmDcH/yO7I3JEQ/4UuAKr0q7ShEBwLFwpXqutyl+tJZrak1cxiF39XsLaejoXBf9f3S9kpnf5xp6a3DxhFP1FrB2ljWtN9rke4Zd7rES0zEk7/Gz0a7NhjSXbRLMvgXGZVQ==,iv:VVYVx7PZH2qDrsgNrIIgoFRd6wtDusm1D78Z8/zm7tg=,tag:tCjdFv/kxmlYfDcNfZ9lDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-14T16:17:19Z'
    mac: ENC[AES256_GCM,data:YbJH2veSOR3yHh/86+txIx2LGbXvwx9fkEwTMo+KbttRRSUcrpqsyha1zjX0ECqHLUieXvMEd+6/qJnx6TdEPWUV+AGGSvqmY+UXXhg9V1nm+ivTWczxi0hIGTlaqOULvAF/8dI510Hq+aR0h8Y8ouaj+UxqCmD3qY775pGXqhY=,iv:QUlH5NeF4FShAIBbfHfk2TT8sspi1DA+VEThZ1SMNME=,tag:EFGYCMnLHWD2lmjYCIIrEw==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
