apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres-operator-ui
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://raw.githubusercontent.com/zalando/postgres-operator/master/charts/postgres-operator-ui/
      chart: postgres-operator-ui
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: zalando-postgres-ui
        namespace: flux-system
      interval: 5m
  # https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator-ui/values.yaml
  values:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-url: https://casa-editor.pub.${CLUSTER_DOMAIN}/outpost.goauthentik.io/auth/nginx
        nginx.ingress.kubernetes.io/auth-signin: https://casa-editor.pub.${CLUSTER_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
      hosts:
      - host: "postgres-operator.pub.${CLUSTER_DOMAIN}"
        paths: [""]
      - host: "postgres-operator.home.${CLUSTER_DOMAIN}"
        paths: [""]
      tls:
      - hosts:
        - "postgres-operator.pub.${CLUSTER_DOMAIN}"
        - "postgres-operator.home.${CLUSTER_DOMAIN}"
