apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads
spec:
  capacity:
    storage: 18T
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nas.home.angelnu.com
    path: "/volume1/downloads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: nfs-downloads
  resources:
    requests:
      storage: 10T