apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-video
spec:
  capacity:
    storage: 18T
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nas.home.${CLUSTER_DOMAIN}
    path: "/volume1/video"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-video
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 10T