apiVersion: v1
kind: Secret
metadata:
    name: statping-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    statping.yaml: ENC[AES256_GCM,data:8fpviidDwhZD82X3cn92h5/gHLPwKb9qtEVaE9lwfMDQ6lp5Dx4iUxzt2YF/nlYppTLx2WgsJvBKyKwTbax4KpgQ0hqEgnqqxp/SSukst96ylDat9/Jrwam28mGmt0VWjcnw5+ptALARXmC/hGGgZ5zMg8ld35SLI/Os5DiU6H4zbSS3ZhYohCVEVNhWhyD5WinZo3s/R3Lf9F0mok/rN4cP0cH+TwKIQeKg97KFiheXbRbtzZOsNRP44w==,iv:C0maExh984rhFDMOx3WoscAcz7U0jSJACdsMVWrhjLc=,tag:iO/BLbgdFvEw3wiVs0viVA==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:Ae4ZcbY/rSraJy8hvbGjN9C/QaLRTT9Kja7SLySwBcf+XhweQtxnZpOHT7BO8+SQt2bvCyJrjY0LGJ9LG5cJh4jixGg1zfH6E0/yf7cdgxUwGoX23TU=,iv:HYfJJCh6Zzm82pV3T9OAGhL9xrlxGM0fl9EZyJ5UH8g=,tag:ycQHXRLIB3sTL+07BO18Bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-06T18:23:47Z'
    mac: ENC[AES256_GCM,data:AVvBpFGIkzN1TZjANEUK14yT2KAyFQOzBh81ZXnkZdDjku/eLeR7pissd54zrPN5IPzZxMpu4sGKr1OjkdrB8kYwMetUVealXJ4vd+pF6LFxcaZJW4FGtwrb1qcCI3v3QQKHpRuSa3BptsESEdZPNGxXjfP55B7qOfxGibAmaeQ=,iv:QP7Lnb3Uuien+LdPmaMXlsyc2KRmLu6fOTuL3nVZA+g=,tag:X0CvePscwT5UEQ33qoZmvw==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
