apiVersion: v1
kind: Secret
metadata:
    name: github
    namespace: flux-system
stringData:
    #ENC[AES256_GCM,data:UwwpSKute8UAYq+sqizF/zUvB0ri625FBw==,iv:RsHTCMY45r5WPpywg4DFGn+ZiuS5AXGZE1sQgUYgE7c=,tag:4oHnwGRXbkjZIcr+hZBfLQ==,type:comment]
    token: ENC[AES256_GCM,data:94ZQKfGL9REWmj1o24bLputCUcoxGDr14e16cgOIHFAlVTJgAHB8jA==,iv:VTCrjCMW9kDReuDIdybfOkZCes3J0nqxT0ujC1WodAY=,tag:X6G3AuNqrAcmCIDnm2U3eQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-16T01:56:49Z"
    mac: ENC[AES256_GCM,data:ezj7I1jZmXk/gwxIzYH1hdsDA3Ph4kxwkBXWpzBGkQ1YOP+BSmMVewkxpweyxd+6GIEPePhZyEmxBpbClR3lAEX+VWAu0e2mYz7ryyAC2WMN2V/xUzdnMPGS0I1KhRpoIrehB50qq7/F5wobdARiIIV7LjYcRLQg+/DIi2xrwd8=,iv:dpgOpnkEDz417NQAbUJdKHS+6dY6hZgSWMbbkAkDqu4=,tag:yYNY6NCxn0h1PkyKHs7qGw==,type:str]
    pgp:
        - created_at: "2021-02-06T22:19:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/8C9XUcea9/KWIdpX24KB5y7OpYPA1F0F/zKAoXpPejUS8
            FNYXUUaDohzBXD/E40iEUMR/WoLWS+brRsp1bJkq7ihPVwXr8o/p1AceDZY211vi
            odFZ50zDOuFxKWja4HXqEVW8sPW5THNiJprsVIJVe4BRxc1eVD/7cm76S/M+urXO
            8L7K+N2IbZtLxyR9boWeDZj6aJI06skcZMqC6WBCrV+oGOTbVqLNwUXpa++fefkm
            d/tv2hLajX784s918tbzGrC6/HVdReAc5BNp5/L3RnCR4rXLPdOfy2cq6MEmSHeh
            SMI7Scpw/O6a1qFkfVyKPjY5f+05PsoOrt3cvbe4uPHFU4U8QNeKiLfeViQAd+va
            DmAjcrjxKEs9Xw+Hx34G0rtAqy/VeNRLGhQz3AAbzjqXVO8gNh2fGr5MFkKgQDj+
            Y6J1d0ksNhwGRu0gol/LT7ti/uyV11rsCmeycJq9CUm0aAed59a+aENPqA5hPRTp
            fuqDuuNVzCFz+4jTcBm4QK0kCcQBGHaTueAj45+FDnBzN1DRbjK/9o4fA3ncGs06
            F+dig6UqFF22u8vCKpYwuhdwo7Kb4Fza+pAAcH42Npe0CNaUYna1Oy6+LO2fMrsm
            iDnSIY85UOhxeiLFNQ9gu2YsFXQ7wHrgZCGECvAypU/nJLqHdYTrEXVD8mpX/KPS
            XgGS2XUYd7DnNiJbQ1KAULc0mkapvX6M7dv4q2ZPfg5QOBy7jNLPKOa1Wr78o+8R
            /DAP//v2+I/+9M9inAxbWUyH7FqvgH22AugsmIrsAUhuIr+cmSG8LlYMxSWQzEg=
            =rVWE
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
