apiVersion: v1
kind: Secret
metadata:
    name: tt-rss-helm-values
stringData:
    tt-rss.yaml: ENC[AES256_GCM,data:7YMPG7XFgzpDZ09EA/nefI/jx6teo/VAY0ssiNutN/iee+2ub9CWuGBeC/3++8oPf14nDT/LRDhxqZXbPTvh2bRVtSmMmVsjz86WzexOYt9eRSJdg1/bB0rlus9OWrWpt0Fqj7E4cdn3otCw86a6UNNlrk6/9fWQHsVAOArDAWYhFwylqgFBbBM7B+2glne+alD8D0wdPA+Y7GEviIjx0sqfe+c=,iv:0tLd08j5zSMMCyofR83ennIDg2bquVdEjE4n5DtBqDU=,tag:/glhjr11XrpoxcDvTqxcFQ==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:dP1MElxsL11htasGnrufePXTnXiqp3E4bHXoeySK+JFIuuWRzxhvxUOUUTxjJ9Klosv2CeZNTYHKVv9QMOmooNIHl4ovwHdGNLNK4FL2hDKPixjO,iv:NNinDfY2nlB3jjVLmX5PrE2jSaQuKgARnuQelsbmQwY=,tag:iNKH6Q5dyJbBycubEQFIUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-14T18:39:19Z'
    mac: ENC[AES256_GCM,data:bzEa0XjdB2isq/B1tdzAxcu5rIxgmignw5f5XTWTrP04c5Sn8P1XdHM8R0GxqBPF5XTpr9MLiQtqwNZovKJOGUT0V9AAyrBRNQftIVKhAW3q/rK8F/cNSqqW/FjxdTwPgMUlssJLJKQApK8eXWeIsTh9bFUIxlluWQswvR3cd10=,iv:zxdPma45mx1j3iUFswz+KaTX/vdD7SRdlV48U+uamZE=,tag:UMy8JDM+gm/4TuXi75XOoQ==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
