apiVersion: v1
kind: Secret
metadata:
    name: tt-rss-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    tt-rss.yaml: ENC[AES256_GCM,data:9UmRqnF78I92jIgxv3fAox+D7SijK05oXtgMe5AJg7KZzmlmSQU44Nw7qd2qAL1AscHDMQVWdPEHtSyioFiwycR+DeLjMCor0KAeFUpP5LjmKb/VDL89N/YqOEew5umZpWIJ+R1FdGWYKb9lmjLAlXWERoxVR0HGSy5fGLZwK6PJgzrKBMlzuEqmWXOqGzfl4laU4gLVzz+HTqxgg+NzXD5HTQOzbY4qu9T6Bxd/DvA+Vs6E45abaLzrtpHoeBS4onbP2gedKDPW6gUX+0CaXhCetZCpIf4l1jdVQMA6b9BnUTsZVrTad3jtWTB4kAJ4Xx4bsMyQqWQ=,iv:ZrMcdVgoMFxmALaHwSCMtvVVe/GMbCENZEjRElvnY4A=,tag:oMmiLqqEsGtAXXofavsnbQ==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:dP1MElxsL11htasGnrufePXTnXiqp3E4bHXoeySK+JFIuuWRzxhvxUOUUTxjJ9Klosv2CeZNTYHKVv9QMOmooNIHl4ovwHdGNLNK4FL2hDKPixjO,iv:NNinDfY2nlB3jjVLmX5PrE2jSaQuKgARnuQelsbmQwY=,tag:iNKH6Q5dyJbBycubEQFIUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-25T22:41:43Z'
    mac: ENC[AES256_GCM,data:S7V9YesGqWQe+alhQPyoPA4tBrfPjkbqLxrc0fg8/704FZxJdx9BbhxdqZLa25VUzU14GVw0j8+6UMQnJpIPYru4e83j4L57/85VEZKh9wckkmtvsSaRLikkOTodDdLjbjq3caQpcR3/E171r/MOmaIr1AKL22ee2+cO8ZwpHiw=,iv:32ZrlZkvZLOiEW02Ewz0jjOgyyNeBTW86yveqJ/Stzc=,tag:Eowvb23BgGGJcfOeFEvdHg==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
