apiVersion: v1
kind: Secret
metadata:
    name: chirpstack-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    username: ENC[AES256_GCM,data:ZOCEVhToMP0=,iv:x3ILT3tytpS6X9qMUwvEHlw/gQ7FRiwZXzO/ZZ9zgFc=,tag:S1fyiBThQKlOhbZ9vdsykw==,type:str]
    password: ENC[AES256_GCM,data:4OJ72/HhS34Tj2Fsn5jBycqGmSfJqNP07rUaG+3cpG7ipWUrCFU5ozPvkpqAJJ6uTl9dzz8jBNO8lRW0yeiJ8SZKDQ==,iv:4V3Gnx8RBV1v/VEAQ8PEmS6SZYiUEEou9bAUcpiLrsY=,tag:9Dwefber8NVpLEPJcN+8lA==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:sOT5lXEnm7+CD620tvRZ7zxF7Gae5/u2VLj3UMK0BeBxYuKLUhB+FNt2SpoIRQbcO5Cosa9a9MSy/UoRp3HXeYn1ZXGAiqZi6u9kvGjBGUsPu+qr+h0XYxYwQ951,iv:pE3Gz+B56XM6Nz/6+eD+AHRjY0j5pZQNhHMO9IlF7Lk=,tag:bUUBkouZybQTFepCO4/Vxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-30T19:55:57Z'
    mac: ENC[AES256_GCM,data:utPkkl50CxrEBOt1KYAfaZyv0adPF4R+bZcNtsahFhI6ozR07yUAda2F5X5p/+0HOC/X3U2JCi4+DE9i5PgOaSo7FMVfgl3xCn16k0OYZI6mIvKOjQnu4DAstclrm4PJ27Aay9W2Y1eux8vQSlS6XLU1TJLi3gG9hKCmegCy1MU=,iv:0IprCldhmkMQfFAuDtX31ZQAtSFkddJ4hIBzaWMI2r0=,tag:0geDYL712WlfLZ3haiP8Hw==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
