apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chirpstack-db
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://angelnu.github.io/charts/
      chart: postgres-cluster
      version: 1.0.12
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      interval: 5m
  #See https://github.com/angelnu/charts/blob/home/charts/postgres-cluster/values.yaml
  values:

postgresql:
  users:
    postgres:
    - superuser
    - createdb

  # -- databases to create and their user
  databases:
    postgres: postgres
  postgresql:
    # -- Postgres version to deploy - see which versions are supported by the operator
    version: "13"



superuser:
  #password: set in secret

persistentVolumes:
  hostPath: /media/db/chirpstack-db
  replicaNodes:
  - server.${CLUSTER_DOMAIN}
  - server2.${CLUSTER_DOMAIN}
    

dumpBackup:
  existingClaim: nfs-kubernetes
  schedule: "@daily"
  subpath: "backup/db/chirpstack-db"

  valuesFrom:
  - kind: Secret
    name: "chirpstack-helm-values"
    valuesKey: postgres.yaml
    optional: false