apiVersion: v1
kind: Secret
metadata:
    name: chirpstack-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    username: ENC[AES256_GCM,data:ZOCEVhToMP0=,iv:x3ILT3tytpS6X9qMUwvEHlw/gQ7FRiwZXzO/ZZ9zgFc=,tag:S1fyiBThQKlOhbZ9vdsykw==,type:str]
    password: ENC[AES256_GCM,data:4OJ72/HhS34Tj2Fsn5jBycqGmSfJqNP07rUaG+3cpG7ipWUrCFU5ozPvkpqAJJ6uTl9dzz8jBNO8lRW0yeiJ8SZKDQ==,iv:4V3Gnx8RBV1v/VEAQ8PEmS6SZYiUEEou9bAUcpiLrsY=,tag:9Dwefber8NVpLEPJcN+8lA==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:oCxoJNfTzooyb4IBbTb8YA7kcxIWNhHTVXAalFgtzrGeXarpuq06zqMTQ7Vh3LiFD067iLBFZyGdhAhhnJDdC/Cjj9BCS1X+T1hhnNVLXJYtBAZoyxR+,iv:nqh0kaDd3AFKFptYS8Y10oYxA0du5QtMDUbs04QmuXM=,tag:RFOocs6XH8dKD8B5Bn6HZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-18T23:11:17Z'
    mac: ENC[AES256_GCM,data:vhM8RkpDrXcJ6I/Vg+tIfX561kEjxmyJfLd/teUJtHIqI02rTJc2uH466Dc2ilWnZIuIyVZjFxAca0RSUFz4neFU+Mk1V5oUyfQZIx+BgwPHVqo1DTbo1Y1xB1q923XIwY05X4sVtMCgYltHGR9kSZdNF7BapwO1zy2tAVEfn8g=,iv:xNLld6VFHOpLiuvCVvN5VsGFd5cvLmxBzAxsS9cxmGs=,tag:Non+ZfHg4DOX5JtzC97sOQ==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
