apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - chirpstack-packet-multiplexer.yaml
  - lorawan-server-fs.yaml
  - lorawan-server.yaml
  - mosquitto-fs.yaml
  - mosquitto.yaml
  
