apiVersion: v1
kind: Secret
metadata:
    name: ceph-secret
stringData:
    key: ENC[AES256_GCM,data:sMeaWOB+thb6NAk6D5af/PQZnjGuxgEwEE5WWHsQW3LuXA6zZnAPfg==,iv:PVMi2SoK5PfzFOJhIPwx1x/cgepBnyJIw3GtFbUper8=,tag:277nLH4+JrFVlGU3EfYPnA==,type:str]
    #ENC[AES256_GCM,data:h5NKT6Fd2Vy+kLWIb0oDcBrMt5tQD2/IT6NHEeHQUPQ=,iv:2elIvWQJLYMAOXO9OVFZvgWTPbsKssY3Vi+BujhlGFk=,tag:pSHQwTC5G52jzXKwl9ZQUg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-17T21:56:13Z'
    mac: ENC[AES256_GCM,data:eZsGvvb57bGue6460sCZ2+adltCcrYFV+biJaSRBEHhVPzcBsghWWjjL/Ps+sNoQsGdijhgXTzbkluAfs1bJMX2cHvdQZMwDLPfvKBaBv3Y8NTiWhE6d1FvSd8eCobpJiU3XV+BpifSKHq/gOE47PWk6UI3GHkWJj/id5ZIb3S0=,iv:pY1UWH5S1JKJOfQ2nwh5WKLoSQC24/JxjSent5/SvBQ=,tag:+89GPArsoqecPmnnXIEY6g==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
