apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: retroarch
  name: retroarch
spec:
  accessModes:
  #- ReadWriteMany
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
#   storageClassName: longhorn-retain
  volumeMode: Filesystem