apiVersion: v1
kind: Service
metadata:
  name: retroarch-tcp
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
  - port: 48010
    protocol: TCP
    targetPort: 48010
    name: sunshine
  - port: 47984
    protocol: TCP
    targetPort: 47984
    name: sunshine-tcp1
  - port: 47985
    protocol: TCP
    targetPort: 47985
    name: sunshine-tcp2
  - port: 47986
    protocol: TCP
    targetPort: 47986
    name: sunshine-tcp3
  - port: 47987
    protocol: TCP
    targetPort: 47987
    name: sunshine-tcp4
  - port: 47988
    protocol: TCP
    targetPort: 47988
    name: sunshine-tcp5
  - port: 47989
    protocol: TCP
    targetPort: 47989
    name: sunshine-tcp6
  - port: 47990
    protocol: TCP
    targetPort: 47990
    name: sunshine-tcp7
  selector:
    app.kubernetes.io/instance: retroarch
    app.kubernetes.io/name: retroarch
---
apiVersion: v1
kind: Service
metadata:
  name: retroarch-udp
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
  - port: 47998
    protocol: UDP
    targetPort: 47998
    name: sunshine-udp1
  - port: 47999
    protocol: UDP
    targetPort: 47999
    name: sunshine-udp2
  - port: 48000
    protocol: UDP
    targetPort: 48000
    name: sunshine-udp3
  selector:
    app.kubernetes.io/instance: retroarch
    app.kubernetes.io/name: retroarch