apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nfs.yaml
- release-fs.yaml
- secret.yaml
- release.yaml
# - 01-pulse-audio-configmap.yaml
# - 03-gow-deployment.yaml
# - 04-gow-service.yaml