apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: games-of-whales
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: games-of-whales
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  # See https://github.com/k8s-at-home/charts/blob/master/charts/games-of-whales/values.yaml
  values:
    nodeSelector:
      #   nvidia.com/gtx970_gpu: "true"
      feature.node.kubernetes.io/custom-intel-gpu: "true"

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.129

    ingress:
      # -- Enable and configure ingress settings for the chart under this key.
      # @default -- See values.yaml
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          #nginx.ingress.kubernetes.io/enable-global-auth: "false"
        hosts:
        - host: gow.home.angelnu.com
          paths:
          - path: /
            pathType: Prefix
        - host: gow.pub.angelnu.com
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - gow.home.angelnu.com
          - gow.pub.angelnu.com

    persistence:
      home:
        type: pvc
        existingClaim: gow-pvc
      software:
        enabled: true
        type: custom
        volumeSpec:
          nfs: 
            server: nas.home.angelnu.com
            path: /volume1/software
  
    sunshine:
      image:
        repository: gameonwhales/sunshine
        tag: latest
        pullPolicy: IfNotPresent
      user: admin
      password: admin
    xorg:
      image:
        repository: gameonwhales/xorg
        tag: latest
        pullPolicy: IfNotPresent
      refreshrate: 60
      resolution: 1920x1080
    pulseaudio:
      image:
        repository: gameonwhales/pulseaudio
        tag: latest
        pullPolicy: IfNotPresent
    retroarch:
      enabled: true
      image:
        repository: gameonwhales/retroarch
        tag: latest
        pullPolicy: IfNotPresent
      logLevel: info
      volumeMounts:
        - name: software
          mountPath: /home/retro/software
          #readOnly: true
    steam:
      enabled: true
      image:
        repository: gameonwhales/steam
        tag: latest
        pullPolicy: IfNotPresent
      protonLog: 1
    firefox:
      enabled: true
      image:
        repository: andrewmackrodt/firefox-x11
        tag: latest
        pullPolicy: IfNotPresent
      volumeMounts: []
    mkhomeretrodirs:
      image:
        repository: busybox
        tag: 1.34.0
        pullPolicy: IfNotPresent

    additionalContainers:
      gnome:
        image: x11docker/gnome:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: DISPLAY
          value: ":99"
        - name: PULSE_SERVER
          value: "/tmp/pulse/pulse-socket"
        volumeMounts:
        - name: audio-socket
          mountPath: /tmp/pulse
        - name: xorg
          mountPath: /tmp/.X11-unix
  valuesFrom:
  - kind: Secret
    name: "games-of-whales"
    valuesKey: values.yaml
    optional: false