apiVersion: v1
kind: Secret
metadata:
    name: games-on-whales
    #Password generate with https://generate.plus/en/base64
stringData:
    values.yaml: ENC[AES256_GCM,data:SMX+NrMIZXKgKJLfE0p0+iUccVcu2LeRr2Sm4DBHarJwvr069RCXrseVlXiYdhomSivgPwBl3M7VehqvZ/JNTOutfsFwh/Vw1ugH0OLZuAf4o2F4+jIysW+Qw+zYQnDy4tqZpn9KU3+3BgVNOTz6msuVe39dWsqxcq2anJEBvJtPuMI=,iv:UY5Bv+JlPzwXlecvTXJ7BHhu51RSaUlMsWuPdgHOciE=,tag:fXZ3UMUXgjyAWuY4jljJvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-24T01:35:27Z"
    mac: ENC[AES256_GCM,data:KGsZCz+b2NgFjmhByTw+Z7nY/L79Tv6QrUodrjiMknSiG4xQjRiESwGJ2jYHeTtvoAtYf5l4S3R99GCC4148NJiiJWY7BKTDXuUvwFgtv6XnvP59DgtsTUofgfceN0FQC5xVvDg767KggL83HG62cvvctNEoR0BOjeyWfx++E7Q=,iv:WI0fy8j8BPuhF/AW1WJZkvNr1zAXSI4nj/igs2DJ6Xg=,tag:bbXVIdKwksB0EKaxdmIwwg==,type:str]
    pgp:
        - created_at: "2021-02-06T22:26:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
