apiVersion: v1
kind: Secret
metadata:
    name: games-of-whales
    #Password generate with https://generate.plus/en/base64
stringData:
    sunshine:
        #ENC[AES256_GCM,data:rvm75yn8r3XQf2aExOLhEBrn5VMTzh+rAi1Sy+okuA==,iv:jW7QDGObaE/iAKYSqDrYr8ZVVNEFF8HkNc5em7psQZ0=,tag:mIESY+BMEXQ7KHSTF0waJg==,type:comment]
        user: ENC[AES256_GCM,data:JmDs/2A=,iv:ojEDKSCr1QzNTOVrpOmnRfueo8yC7+ctIlf1xmTC+zg=,tag:82kL0m7/mhu8bbyNdaDCww==,type:str]
        #ENC[AES256_GCM,data:6ZAKyQb4c41vT+8uK+QcywWqc7CDFqH631BWOL7WlR5qIw==,iv:CXhcHyzTfpkpP7++Sggot4lsuUOV3ModrUkJ9FLiCxc=,tag:oo30IzGLBeTq4ReKJFOaVw==,type:comment]
        password: ENC[AES256_GCM,data:0B7K2Lc=,iv:MpmvxtuaxfDpOgz3Fw0h1AnEBgDgZhhEVWP9v+bACNw=,tag:lvVt36gLH7V+OsDayc9WZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-23T23:39:56Z"
    mac: ENC[AES256_GCM,data:30Q0KmvXX19vcf0FxBfRbHFX2DHtkjkYLVEIsFEoLYFYp0SYzO2PDZQAhotM/LiwdbxTWKhzn7zwCTMbKeZRekbAp3y9LahjlWiXQg1986T3P6vYPLP2KGekp72zRYDrNN5/j6UM7+VBMK9uMuPJX2u2F1wLIVzf1T1WuwEAtik=,iv:f7mrunUGK6xHWvJ2jKdeOiGeE7YRRNldyM90ym0vlGs=,tag:78pxvVnaFPboNifyzWNa3g==,type:str]
    pgp:
        - created_at: "2021-02-06T22:26:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
