apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: global-secrets
stringData:
    TESTING_SECRET: ENC[AES256_GCM,data:ZtsOoyATHJk=,iv:ibHJIF9HByPTkilk8FfbMy8OEH/mdtwL8WpRXKoVHMg=,tag:hwqbjiTTmyd0GKHBVIKH4Q==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:G9CIJ+kBQIAWIwDyqp3I/VfmYwU=,iv:U6IFDsr5KOLS+ADONBs62vlPuNanAgrGWNuDp2FNCf8=,tag:0Yt007ZXldVnGhmdR1kh2Q==,type:str]
    CLUSTER_MAIL_SERVER: ENC[AES256_GCM,data:0md714xq4rOI11QxmX/V8sCTTw==,iv:MQvIqpsIcNAeJDmFfK6fpGm4YZ7bt9ce/hPWns7P4Uk=,tag:rIYWq8J/AdGDZxc0QPyeYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-05-22T14:15:57Z"
    mac: ENC[AES256_GCM,data:DXr6YkDmjFQ4b3niBd2Pl7ucaGTZAyH7uILdpzNfET4r65eRd/J52TnWufyO5O0fIT3lFC+6G8pypwpn6UDYs/4N6BBzzg6IGB8T/ObcahZNnSjBqJGuYJC3AOTioVCkBSX7SMhmLgfz8DrCJ11/+WBfhZrqKE67icEEpu4Jquc=,iv:mk56NxbMgi63uH4xkdPovwTul1+kpWLgmuLjZ2/Y7II=,tag:SJZWW5sX0Au++MQbbUev1g==,type:str]
    pgp:
        - created_at: "2021-02-06T22:19:41Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/8C9XUcea9/KWIdpX24KB5y7OpYPA1F0F/zKAoXpPejUS8
            FNYXUUaDohzBXD/E40iEUMR/WoLWS+brRsp1bJkq7ihPVwXr8o/p1AceDZY211vi
            odFZ50zDOuFxKWja4HXqEVW8sPW5THNiJprsVIJVe4BRxc1eVD/7cm76S/M+urXO
            8L7K+N2IbZtLxyR9boWeDZj6aJI06skcZMqC6WBCrV+oGOTbVqLNwUXpa++fefkm
            d/tv2hLajX784s918tbzGrC6/HVdReAc5BNp5/L3RnCR4rXLPdOfy2cq6MEmSHeh
            SMI7Scpw/O6a1qFkfVyKPjY5f+05PsoOrt3cvbe4uPHFU4U8QNeKiLfeViQAd+va
            DmAjcrjxKEs9Xw+Hx34G0rtAqy/VeNRLGhQz3AAbzjqXVO8gNh2fGr5MFkKgQDj+
            Y6J1d0ksNhwGRu0gol/LT7ti/uyV11rsCmeycJq9CUm0aAed59a+aENPqA5hPRTp
            fuqDuuNVzCFz+4jTcBm4QK0kCcQBGHaTueAj45+FDnBzN1DRbjK/9o4fA3ncGs06
            F+dig6UqFF22u8vCKpYwuhdwo7Kb4Fza+pAAcH42Npe0CNaUYna1Oy6+LO2fMrsm
            iDnSIY85UOhxeiLFNQ9gu2YsFXQ7wHrgZCGECvAypU/nJLqHdYTrEXVD8mpX/KPS
            XgGS2XUYd7DnNiJbQ1KAULc0mkapvX6M7dv4q2ZPfg5QOBy7jNLPKOa1Wr78o+8R
            /DAP//v2+I/+9M9inAxbWUyH7FqvgH22AugsmIrsAUhuIr+cmSG8LlYMxSWQzEg=
            =rVWE
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
