apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - namespace.yaml
  - https://github.com/jetstack/cert-manager/releases/download/v1.2.0/cert-manager.crds.yaml
  - cert-manager.yaml
  - cert-manager-dnsmadeeasy.yaml

