apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-media-pvc
spec:
  resources:
    requests:
      storage: "1Gi"
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  storageClassName: recipes-media-storageclass
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: recipes-media-pv
spec:
  storageClassName: recipes-media-storageclass
  capacity:
    storage: "1Gi"
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  cephfs:
    monitors:
    - 192.168.2.129:6789
    - 192.168.2.170:6789
    - 192.168.2.147:6789
    # by default the path is /, but you can override and mount a specific path of the filesystem by using the path attribute
    path: /k8s/production/recipes-media
    user: admin
    secretRef:
      name: ceph-secret
      #readOnly: true
  #Since it is created directly this does not delete it from gluster
  persistentVolumeReclaimPolicy: Delete