apiVersion: v1
kind: Secret
metadata:
    name: recipes-helm-values
    #Password generate with https://generate.plus/en/base64
stringData: null
stringData:
    recipes.yaml: ENC[AES256_GCM,data:9ipSBYDJLwFCR7xx83ftNVxHVTAMvFuEO6+0AHO1Y32d9Y52fvmGKIAY11PraBMCN29GZsXnt0+J/8DthxbLOTspWZcR184OnZU7yscYuOrV4wXGxT/ygjV96SPQY79r24AhSDt16G6N05SMUsKuF73stAdyMgdD5UFVNCcM0SuS1mJ6R6SvpVRTBXk5rJ9t3MTAxaYYjw068qWSbgbW,iv:X1LMaDTfbX67t9yvUwG8kXeLF5DtloNZ2WI/PXAQv/k=,tag:/cTmcmLPTketWM0ppTJKYg==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:GyRyrIA34c/s2PbPMVe4bK0q34P4bONBPaLZLX9eBc/0IkWsWNh5q7I+xc51e0XOx6ct1FQSHwOfAFGlFCmMW614U5SYUshH+CSqp/6RV8XD8ygpSLXIHTAi,iv:m89ZRImzgTxJnzvH1QKxoqRPdvRMuLOL+zcYdDapJZU=,tag:zC2DyrkoFiOiwUXdHd2pQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-31T03:05:31Z'
    mac: ENC[AES256_GCM,data:aBPqVJL7NFi0/tx17rmrTvFutesaXxFV9aOfVdmmZFm8/ufC1F6bWkqiRelMpmCO/30YZEzRJFeDJcHlbvtt6mT431djFNkdBcwYedBvqiGmmmK787aLE6z1UqAS5oOUp/36qQnqrUfG+YnuyM3N2sD1F1o+d9dHT4SZn8+oAeA=,iv:Z0Oy5Ryp1BZmUp4ShAD80iF3Il7i+vLBYJ6FNEOm438=,tag:DRbLXFa/LnAtsSaR6rNvYQ==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
