apiVersion: v1
kind: Secret
metadata:
    name: recipes-helm-values
    #Password generate with https://generate.plus/en/base64
stringData: null
stringData:
    recipes.yaml: ENC[AES256_GCM,data:9ipSBYDJLwFCR7xx83ftNVxHVTAMvFuEO6+0AHO1Y32d9Y52fvmGKIAY11PraBMCN29GZsXnt0+J/8DthxbLOTspWZcR184OnZU7yscYuOrV4wXGxT/ygjV96SPQY79r24AhSDt16G6N05SMUsKuF73stAdyMgdD5UFVNCcM0SuS1mJ6R6SvpVRTBXk5rJ9t3MTAxaYYjw068qWSbgbW,iv:X1LMaDTfbX67t9yvUwG8kXeLF5DtloNZ2WI/PXAQv/k=,tag:/cTmcmLPTketWM0ppTJKYg==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:GIs/zMPtlNj4m4IgC3zB2EeYKgAtLkbmL84pNjjneuhM6ySeMwQgoX7QZYc9aFqCsU0kivK0n5O1sei6+cT20Fu7E4Izl0qdjcR4sKQdDtPCgfIJ,iv:9w3HJoDAM9lYp0H7v7Q5LqHn1EoBJtaHLZOBwu7W9fI=,tag:f1qDnTkudCiXRvuViZzTfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-20T16:50:13Z'
    mac: ENC[AES256_GCM,data:5sbOJT585QZ48uumM39JKakqLDTfWu8Oz9fDslVAI7olkMkciJs1GwtdoJO7QzKHELyVnEXEFtya9p0/eJEdyJEv4iUcPxEwsN4TqJCBrPFqeTBDZW0Iqxll3bDadGqOLipfPYPmrZ3WjH/8uOS19jf/djcWQuJSdShEi+Uuhzo=,iv:vlx0KuVzkvUe3iwScRRwc3o0UBnahis2A0GSYEfskuM=,tag:v7BmMUtF/OHY0bGfu479+w==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
