apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m5s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/production
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute:
      CLUSTER_ENV: "prod"
      CLUSTER_DOMAIN: angelnu.com
      CLUSTER_DOMAIN_CERT: prod-wildcard-angelnu-com-tls
      CLUSTER_EXTERNAL_SUBNET_PREFIX: 192.168.1
      CLUSTER_LB_RANGE: 192.168.1.128-192.168.1.192
