apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raspberrymatic-pvc
spec:
  resources:
    requests:
      storage: "1Gi"
  accessModes:
  - ReadWriteOnce
  storageClassName: raspberrymatic-storageclass
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: raspberrymatic-pv
spec:
  storageClassName: raspberrymatic-storageclass
  capacity:
    storage: "1Gi"
  accessModes:
  - ReadWriteOnce
  rbd:
    monitors:
    - 192.168.2.129:6789
    - 192.168.2.170:6789
    - 192.168.2.147:6789
    pool: rbd
    image: raspberrymatic
    fsType: ext4
    user: admin
    secretRef:
      name: ceph-secret
  #Since it is created directly this does not delete it from gluster
  persistentVolumeReclaimPolicy: Delete