apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: gcr.io/k8s-staging-nfd/node-feature-discovery
      tag: v0.10.1
    master:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: In
                values: [""]
    worker:
      config:
        sources:
          usb:
            deviceClassWhitelist:
            - "02"
            - "03"
            - "0e"
            - "ef"
            - "fe"
            - "ff"
            deviceLabelFields:
            - "class"
            - "vendor"
            - "device"
          custom:
          - name: "zwave"
            matchFeatures:
            - feature: usb.device
              matchExpressions:
                class: {op: In, value: ["02"]}
                vendor: {op: In, value: ["0658"]}
                device: {op: In, value: ["0200"]}
          - name: "intel-gpu"
            matchFeatures:
            - feature: usb.device
              matchExpressions:
                class: {op: In, value: ["0300"]}
                vendor: {op: In, value: ["8086"]}
          - name: "nvidia-gpu"
            matchFeatures:
            - feature: pci.device
              matchExpressions:
                class: {op: In, value: ["0300"]}
                vendor: {op: In, value: ["10de"]}
          - name: "coral-tpu"
            matchFeatures:
            - feature: usb.device
              matchExpressions:
                vendor: {op: In, value: ["1a6e", "18d1"]}
          - name: "flight-aware"
            matchFeatures:
              matchExpressions:
                class: {op: In, value: ["ff"]}
                vendor: {op: In, value: ["0bda"]}
                device: {op: In, value: ["2832"]}
          - name: "zigbee"
            matchFeatures:
            - feature: usb.device
              matchExpressions:
                class: {op: In, value: ["ff"]}
                vendor: {op: In, value: ["1a86"]}
                device: {op: In, value: ["7523"]}
      tolerations:
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"
