- name: Install Bootstrap Packages
  apt:
    name: "{{BOOTSTRAP_PACKAGES}}"
    force: yes
    state: present

- name: Update system (after refreshing caches)
  apt:
    update_cache: yes
    upgrade: safe

- name: Install Packages
  apt:
    name: "{{PACKAGES}}"
    force: yes
    state: present

- name: Prevent packages with versions from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items: "{{ PACKAGES | map('regex_search','.*=.*') | select('string') | map('regex_replace','(.*)=.*','\\1') | list }}"

- name: Remove Packages
  apt:
    name: "{{ PACKAGES2REMOVE }}"
    force: yes
    state: absent
