apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-call-webapp
spec:
  providerRef:
    name: slack
  eventSeverity: debug
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'