apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/staging
  prune: true
  validation: client
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  postBuild:
    substitute:
      CLUSTER_ENV: "prod"
      CLUSTER_DOMAIN: nunez-gregoire.eu
      CLUSTER_DOMAIN_CERT: prod-wildcard-nunez-gregoire_eu-tls
      CLUSTER_EXTERNAL_SUBNET_PREFIX: 192.168.3
      CLUSTER_LB_RANGE: 192.168.3.128-192.168.3.192