apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  #VALUES DIFFERENT PROD - STAGING
  CLUSTER_ENV: "stagging"
  CLUSTER_DOMAIN: nunez-gregoire.eu
  CLUSTER_DOMAIN_CERT: prod-wildcard-nunez-gregoire_eu-tls
  CLUSTER_EXTERNAL_SUBNET_PREFIX: 192.168.3
  CLUSTER_LB_RANGE: 192.168.3.128-192.168.3.192