apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  #VALUES DIFFERENT PROD - STAGING
  CLUSTER_ENV: "stagging"
  CLUSTER_DOMAIN: nunez-gregoire.eu
  CLUSTER_DOMAIN_CERT: prod-wildcard-nunez-gregoire_eu-tls
  CLUSTER_EXTERNAL_SUBNET_PREFIX: 192.168.3
  CLUSTER_LB_RANGE: 192.168.3.128-192.168.3.192

  CLUSTER_DB_VERSION: "13"
  CLUSTER_DB_NODE_0: test-node1
  CLUSTER_DB_NODE_1: test-node2
  CLUSTER_DB_BACKUP_PREFIX: "backup/staging_db"