apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-helm-values
data:
  common.yaml: |
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.5.0
    
    env:
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_TIME_ZONE: "Europe/Berlin"
      PAPERLESS_CONSUMER_POLLING: "60"
      #PAPERLESS_CONSUMER_RECURSIVE: "true"
      #PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
      PAPERLESS_IGNORE_DATES: “1978-09-19,1979-06-12,2010-2-8,2011-11-15”
      PAPERLESS_REDIS: redis://localhost:6379
    persistence:
      data:
        enabled: true
        mountPath: /usr/src/paperless/data
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_SERVER}"
            # path: set in chart values
      media:
        enabled: true
        mountPath: /usr/src/paperless/media
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_SERVER}"
            # path: set in chart values
      consume:
        enabled: true
        mountPath: /usr/src/paperless/consume
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_SERVER}"
            # path: set in chart values
      export:
        enabled: true
        mountPath: /usr/src/paperless/export
        type: custom
        volumeSpec:
          nfs:
            server: "${NFS_SERVER}"
            # path: set in chart values

    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 4G
          
    # -- Deploy local redis instance.
    # @default -- See values.yaml
    additionalContainers:
      - name: broker
        image: redis:6.2
        imagePullPolicy: IfNotPresent