apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant-db
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://angelnu.github.io/charts/
      chart: postgres-cluster
      version: 1.0.10
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      interval: 5m
  #See https://github.com/angelnu/charts/blob/home/charts/postgres-cluster/values.yaml
  values:
    persistent: true
    localPath: "/media/db/home-assistant"

    backup_schedule: "@daily"
    backupPVC: nfs-kubernetes
    backupPVCSubpath: "backup/db/home-assistant"

    replicaCount: 2
    replicaNodes:
    - server.angelnu.com
    - server2.angelnu.com

    #If you change this after creating the DB then use psql to set the password manually
    superuser: postgres
    #superuser_password: set in secret

  valuesFrom:
  - kind: Secret
    name: "home-assistant-helm-values"
    valuesKey: postgres.yaml
    optional: false