apiVersion: v1
kind: Secret
metadata:
    name: appdaemon-helm-values
stringData:
    appdaemon.yaml: ENC[AES256_GCM,data:soqetwyU1ROGT3+iBGz6XvrIYXxwwCGogwl+lPhoFfdd6PwdLCE8YuVFPA/GImVrG3WzrfEnGxe8sNymxKBJ4C1z4IRvQB6E+A2ZleEeTcEVOy2rXlrH/sjyh0RFTkQ2A/dR/A3zX008tLm3t/9YM7uHUBFJ8CzTehpNK20fOCV//IPWsUBoFWS/K21yrOKrDQukvFmVMp4MinWfO6lYagtAlvtJvBPfTC6fb/tHJuPuoB+4R0MNd0+YEg34LFwAwEux8tueNUmxhl2+cQdK9nZNbF38QZcN6kunNy9ji7bRVoniQ+Che4RzDq5sdiO8Z5FwIuvlnjAkzn1oFa7oSzxVnKtnLWCY4Slv9SBToOPufG4CG5rnRsk2mlk=,iv:CkBYZjhs3Tv7exFEGJQFMpvRFHHiDXajsICfEp2bXV8=,tag:25LcHEe6sXMJNJ32xMY/EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-06-16T23:06:53Z"
    mac: ENC[AES256_GCM,data:lLFK+XR9rVA82QLYFxfktoOunnRdZRvr+YrSGC1cTaE3qzD6XlmD2xsHq7ikI4vRT4Eg+waN5PR626iwK5s8hkUppwOC6tWXJ4N2/3u9Fnphi1ZZFBNxGZ5Qe0s5UuKbfbnHDZROfu8Zl1W5225eK1PfrKz5WepqLqjrayUTM5U=,iv:0rT0DuF1BObj3XFqVcmPcl9C8mOk1WabpHAxyBURHU8=,tag:66w01wED7aP/mqKFm3eA8w==,type:str]
    pgp:
        - created_at: "2021-02-06T22:26:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
