apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    postgres.yaml: ENC[AES256_GCM,data:yzH7dsLhNvqdFOgnB+JyWKV+hZnI/j1kTdrrbmknzz4bOmvZR6P/m+vUPkcQtnZnaR/LhwaIDi8OGFbg5kG+VlDsQb/S5P6YAiUWV7R8tB2In8RRW85HTOF8,iv:bMYbGFu9EMquG8+9l4GfrzZNo2fwHcN7m2PNINXvdgo=,tag:Q9OyfFzqmhWLcMVvlT0IlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-30T21:51:14Z'
    mac: ENC[AES256_GCM,data:q3aDq8pWUX34LkZWvDQR0Qkr+cIruX+setjqpq/1copM8uT29FNphIVJCAQWpXUbgswyOVyVNsx+9eI8HLl3bawR4/EKlggD3OI7d0dtQnleayXznswD1yRlPM3riRlvOcNwhHEiHGoUP9OOwsDmqwx2uitp0kXf2xsz28r2K/g=,iv:t2T7L1mh99znrNwrr+Btv7mlwZ+Xw231/itHvl/Xp6c=,tag:C1wCLr0AJp0HfUNbpiuG3g==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
