apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    postgres.yaml: ENC[AES256_GCM,data:4TeZkj6gH0A/E74pK9KZjPE3djdkMk2svyGN30uXYHEamyKpEaYVX+TvWypLiHgUcwl/FzMbusbpXx13NhCKhBTcIsxbGSU9/EBQN5FWXzQ055Cm,iv:3MvWk3cUBsZT/PEkf+uGc3ZtHDcr82Mfph+0Gai2U2g=,tag:T6S3ii4Yw+TOQbznw6H+xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-20T14:24:27Z'
    mac: ENC[AES256_GCM,data:z8teJofdrt2aNxozHC55Hzel+kuxHou+AEYfiBWBx2YcI0Rj9cIJfkuzXvcfz/Rfk154u0HXnucIO3Ug5IU95d6L2B2qOR8P/jk602vl2qIFg5gpUXJxQSYtT3+QBEjlSA6eaCIruSGNsvHVwH2wP7J/u+H1owr4sXk+LLBCOYA=,iv:iRhbAwGvr+j4+MQoPt6uBOo8BzekqpyNLobo09NF40g=,tag:x3l7r69IPQgmrtyxwzZYUA==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
