apiVersion: v1
kind: Secret
metadata:
    name: searx-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    searx.yaml: ENC[AES256_GCM,data:eKzJ+aDRNi8Vc1vnnu1VKuCyObcc6g4bMoEc5d9upLOnRM4pZ3YwDFz0wpXY78fcoxLQctA=,iv:sL0cx64Kc1770aizypxkb1E7wARnHnkp+XtnCieSj3A=,tag:2timIUMbkDDCOxWD0greqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-31T16:26:08Z"
    mac: ENC[AES256_GCM,data:F2B17MRXvHRLyECRcSYiDGA0hb6lWqpZbjvwX2mllwfUW1fu2qMNxfX8wfXAxpENL1spFsR/8yciG+NdudSQGh68rtbk+qCKLfMZ6vpNvdA7LstDucot0IoBZW9DBARWSl2PPEWwufmdlRW3wrmJHbx7cFEq5Ss3+HNC7BFbRFc=,iv:55i79xxC83l+e+fUiqXsRhIQn4wdaGZyiKhUu/Dq+u4=,tag:M8QujOpKlW20ExuHqEuY+w==,type:str]
    pgp:
        - created_at: "2021-02-06T22:26:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
