apiVersion: v1
kind: Secret
metadata:
    name: ceph-secret
# Required for statically provisioned volumes
stringData:
    userID: ENC[AES256_GCM,data:KPMlCP8=,iv:2tUK7S1XrIOypLYfXo2hkquIDiZfdyyky2t5bxAAJXc=,tag:hJNn7YCk0BV9TveyKuy0tA==,type:str]
    userKey: ENC[AES256_GCM,data:Qk9lXFSMDUSLgKxkZeO+or4GrcpVCWL6W05jlj7sSepQBzAqFQSC1w==,iv:ElbuaFVNrENyabUqX3ZeAiiEECltcGLmQO6S0STIFiI=,tag:T1yuQEH1gEYnIk6D8IoVSQ==,type:str]
    #ENC[AES256_GCM,data:zHbqz61RAT/mw0dw85LCmWcBJO1K4MvdbTF9S+PIscJ9HkOJ8yL4AqKoCSDg,iv:N/wQEYQlejPDUuE/L4bIImtCd5QYn48TIYwh6oRJp5k=,tag:S9uiZRERAo1DI2hCP+k49Q==,type:comment]
    adminID: ENC[AES256_GCM,data:qi9Q6KM=,iv:7lsSiS0P3jLw79j0dnVPA1yGKWCb3XJ+U/Rq43ARSqQ=,tag:xg4tKTL4VcyZH4yGbY/tMg==,type:str]
    adminKey: ENC[AES256_GCM,data:WE92EfHTc6+ySV5cwcqw8WGW8HNEGSBqVslcz631fc5gnCJu7tq7DQ==,iv:+71TkYFkMPrJVdDBfXJrFuK6xvOkVULhQqMJ/P8bKU4=,tag:YDLUv6FPJSPD3Zvft++6uQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-04-19T05:40:27Z'
    mac: ENC[AES256_GCM,data:UTEHm9D9OJn0Gz0Vv+DD5qhdVvHTFdqsTl0StM9SB1uzxqHxwr17a4kBLl1Hw65F2yWEGeoGjEsFX5jiZJH1Is/gfsUxrgqQ13yCy8Fu+eBPTv0pjl1XzTFp5Ff/1YvhrmP0ZsNii3PKWEd7d1vAONSbQDfOsGOjGyyI65rzsI0=,iv:L0izx6N6+h9eZtd8khoci5WaSHtih6CnGgt6iyPwGWQ=,tag:7iRa1AGRVR3K3D7i8e3xXQ==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
