apiVersion: v1
kind: Secret
metadata:
    name: deepstack-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    values.yaml: ENC[AES256_GCM,data:1C/E8eXrMByDtSCtcd/Eh3xhJVj5UUTVaQNRtKMzai9AJa14U9BMS2m1w6tK3XdoLblqYC35Hi9i3KIPWuSVEsAkCEAPsu5cS2BAHcTvyKAfwg85j+PdMVGj9kHuxD4iVdZrw2vkYR6LRP0NBTF3bfLLMDJoggvLeWdh,iv:HMfmgfw2kIeWUN5rQ9IpfA2MYtXAalgn8cKNBUB/KkE=,tag:OLqc26ErT+9UovZz/NfE4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-13T16:38:35Z"
    mac: ENC[AES256_GCM,data:AdwNTksZf7tDDp9yDdCP334vG5jipW0rYfZlWiO7awM5RNW1Oj1e5EUIWuUWA4w1XGRkdjlozIlQVLYpnh0Lq8IdGa+Z5HIO7us+LyTVqAo9LvrMnDytAFFSTVOn/x+RdaJZ3mFTFoOFfwa3aFulMqhEZpvswwZAqabQpBhBGwA=,iv:5FIB3wHST5R2U5OTpHypJJb4DTBVIzut/46ePj2cp4s=,tag:L/BgrPKv4SDxbO4RWqtvIg==,type:str]
    pgp:
        - created_at: "2021-02-06T22:26:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
