apiVersion: v1
kind: Secret
metadata:
    name: tt-rss-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    tt-rss.yaml: ENC[AES256_GCM,data:HRo/7X+NQwXcy8e2+YqXVq4zFZx0u8L8RYEALLWak7CWpkyeVoTNUi3NmqL/90lSOqUySmDEDJXc23BKYhCL/ZmcG9EyhQZF3iUAugG/MInWg9U6XuDtI5Sspg4NGSCSfY7HpCDdgRFg883UJxzuS1VqkzPmHldLrpU7/yU3zeMTUnG5nmAcFJ+kw9K0S7dnIXxxlxx1nCHg6Wg2yRBEjWv0cFDmFkGXhz5Z/ZX6c45AFxhcPM44NmczSophKMBJdsg5tiRqz/tFY8c57mO55GU+xRw9nMOoUTFzm35W57Mea68KkQWMT7W9YPr3FoBk26PMlH4AEinC9z5VCtni+iV7bC2Y7n/QwMBromLbZlnjL2xdzHkJrJu/CJppCQ0i68ocs6Mq/EfypjrWzUoRcyD1xl75++R2/gmxH1KKCggUImpYXPEKkewAM8Cv5SfvNeWzjTAv0YRX1mrIM08IE7vaCCz4QzbQs3s/f1oQ0CZV0GSmqEvkbE1StDutREsY8VIbMOUzNSV4MmkREX3sK38NJYs7r+Cf8xXulfroyVPz+qGoW1qJ6xQf0Mi3WMHSebHpcIBR3CXZtfj4FikBgvPlc/zGrxVGSnfxaAGxUmxpDmGWv+f9QUTSCRJGV98JS8xgdF/3FyOyg5PjPA==,iv:jiNVR3RSW3s1GRBnu0rIvNI3SrV2TfSTIxkYE/3VwJU=,tag:zOz0x/ObCbfXVjSJN7nuWw==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:w3At86a1HsiVvHCF9WDWodpB/n9M8onW46G2KVrPdcjIbSfeMQlLrnCn0wo/ZJY7N7tJb6utKFdL/poZGoiMXfbZGznHczu2lmHuTub47qgXkIferu+6gHZd,iv:ue2ojup75CEqpz+e8c8K5UWjRCTFCJeUeUlOlg0aFqw=,tag:Fm8T0OfXLk0qVpUwvZQ81Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-03T15:22:43Z"
    mac: ENC[AES256_GCM,data:Rf25t+CqgXLCqE6eWL8kNKR/v2ixrOC6KkUhkI9sd/jXUch/ZWj2D0+TPEuQ1x2hGVF79JlQKFhQEUeEyYEr9IV++fnjme3Hyz9VRRUMY2L12Ilb1UU5rWyPmhUYuUNubitF79J4h14KKyWuUSE6n4vl83OowE3cIcuPGiS3Gqk=,iv:OQxuH+NzEMdFwLNZDUP9EaXlW5H0tBoYPBeMwJKy57U=,tag:MsVBnqmOShkPeUJGvCkelQ==,type:str]
    pgp:
        - created_at: "2021-02-06T22:26:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
