apiVersion: v1
kind: Secret
metadata:
    name: tt-rss-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    tt-rss.yaml: ENC[AES256_GCM,data:vsYmUy0Wf7/M0R3HomaLLYEZrzf4icaCv/tIFywHF3JhMEx3yEKNZOogHJ39uZQnRtFqjvXv5BrEA2PhQjsDbRu/lfEGw5jPTQYHuJurv98/6S1FcLcFAUgz3lDjx+CH5YOjZ0Qou4mKCiq+fJe+vfWWJKmyLodTuwKL47jxI9DCAl3qvASMHHGD3mjWIhBbMtTLI1OqzJmCWxIs4KBY5fSqKr9L4+bsbEQX0O0iVzeSUNAh8kqs3IC7eQ+wIP/RYoc3ghOMt6ugopKt1ShLWIOE+aJ2vyHEVOkX5cKJgElF2ioStDXKR644rrbFZNWrnSf+Woha6KIOT6B+9VnG5ibTFPA2Km8ru/nBPUD7Dm7ZDexWTN1xO3bk+wJkZ5i2sg9JzGsND83Q57OTSozCcQ8pTJ35ayXx03qHObjcfAif5ISI5VVV1go0TaZ3s6mA7wEXVPi9ObJy9MJIRmBQwJtW2bGy/2igGI2vMAoLqS2ID5lt97tDCyH4TFe8AYG7zy3jE9rsynHNuIfnDfBePGypowDsYVz1CreHObNrYvO0rw1owyxdeZGM5WPsA8Tq/3cIMhQdHkTbDmrIsfaRSDpmSg4nCKfUsWboABAkpPK5Xb+oRU/tNZjA7QU/iYSr4gk79vrsSUWIdoIqhZGO+65KGvK0dg==,iv:bCJij3TdcSBO339Gjg91hx2ltcu8J5ZpkcGb2oVn5wI=,tag:Yz/okms/vzPlgQVefkqwPw==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:w3At86a1HsiVvHCF9WDWodpB/n9M8onW46G2KVrPdcjIbSfeMQlLrnCn0wo/ZJY7N7tJb6utKFdL/poZGoiMXfbZGznHczu2lmHuTub47qgXkIferu+6gHZd,iv:ue2ojup75CEqpz+e8c8K5UWjRCTFCJeUeUlOlg0aFqw=,tag:Fm8T0OfXLk0qVpUwvZQ81Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-03T14:42:41Z"
    mac: ENC[AES256_GCM,data:ZRqLxv2GRdZbtRls0Naw0UB+KliRBwPo5AfBH5it1qAjfisaN0+P3ROPz2ZYjYXHQEYhG+5qmIRkMWRTnyXUELza/Yu2N80e99jSQscjSmENtL0GyMV7H7bGhxYMBeE9egrjOQ05Es0pCIKwvK1SXIfff7G60B8WUHzIREUz83o=,iv:r76sO6+vQa3Ew1o5omm2hPugJgNdWqCSyX+/rSHr9Xg=,tag:Z5nnltspbrFThfSl/ytqrg==,type:str]
    pgp:
        - created_at: "2021-02-06T22:26:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
