apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-gitea
spec:
  storageClassName: gitea-storageclass
  capacity:
    storage: 18T
  accessModes:
    - ReadWriteMany
  mountOptions:
    - local_lock=posix
    - nfsvers=4.1
  nfs:
    server: nas.home.${CLUSTER_DOMAIN}
    path: "/volume1/kubernetes/gitea/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-gitea
spec:
  storageClassName: gitea-storageclass
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1T