apiVersion: v1
kind: Secret
metadata:
    name: gitea-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    gitea.yaml: ENC[AES256_GCM,data:w1IWdmha5e8jNAEB42esOVDjxK66MJTHmXqHC66gbc8i/VGte+WAKKcwrcLqgYba6L90zC4+EHNMDnS5VqXUnOnElVEmb6MgV7BMsJJ9Tv8cI32NhDyHwAOyyw8dV0zFc1pCEy2zrj1olHuassF8h7bE4ip2TrLZbiBiOUML/KZHV2HKsKsLohqzdMZYHZI0xUcVGsbuxhEO3uTEfx+zaO7+RON5Xxp5mmDHlTVigJUkFVK+/pq06lORsSqcTI64VR54erE/yhpAHmGDpS1kzaIgVOxpGfjZAm39Y/wpwXEAeHMSAZgZMFTTWKjXXWfvzsz285cV10ayco5Mvyf68ytgCiMxGDSNG/M41f5XhnLaNNGnjZsa8/DAKHc2DvOr,iv:bY/vPbAVBIaME6ZbOBW7/QcT+yrs4CaPE8ZWDsuNH38=,tag:wAjffOt8SvgiXmb2dDULhw==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:Yc438cgwf+l9Mi/9YocEB/NRSdjwkSVCFEwa1Kf4HF+bngncCTbgpHvkJEnuKnDakDxTybpJf2C0wB5+6wdWfWlaV/53I8NPTgU3QjFrafbvCgoGxGOHTh/xttEjo7UhsbUlIQ==,iv:+yri9D9ncB4Nc9HYtETGh2dBYi+1fGfhimaca7xbOTs=,tag:+x/nYmzKb/XHymQLZHoDWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-20T14:23:56Z'
    mac: ENC[AES256_GCM,data:Ng7HlBFuPBGskAHWLwj6btLTlEJVhosahGaAhRtEdn+Zv+LiaDc7A+x4DyQz3KDiuew6yEhby31OM2B9yCZ7Y5y/EDeKNvWpqObMZjVLKp0HEz/YFbaEbwbphnWiVDQcuQeI5zsZ1fVejzgsb70JDHEVvnpN9476X5O5ffcIaEg=,iv:O/5CaFEJCmQYG3aNN6Xp5Rumq0BRORckOLA0DK5qztY=,tag:G0I2wrhgLG7GpFzMiGwgXA==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
