apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - apache-musicindex
  - comics
  - deepstack
  - esphome
  - gatus
  - gitea
  #- gow
  - hajimari
  - home-assistant
  - homer
  - jellyfin
  - lorawan
  - nextcloud
  - paperless
  # - plex
  - photoprism
  # - raspberrymatic
  - recipes
  - reverse-proxy
  - tt-rss
  - unifi
