- name: Set labels
  shell: "{{ KUBECTL_BIN }} label nodes {{inventory_hostname}} --overwrite {{ item.key }}={{ item.value }}"
  environment: "{{KUBECTL_ENV}}"
  delegate_to: "{{KUBELET_PRIMARY_MASTER_HOSTNAME}}"
  register: result
  with_dict: "{{ k8s_labels if (k8s_labels is defined) else {} }}"
  changed_when:
  - "'not labeled'  not in result.stdout| join('')"
