apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: recipes
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: recipes
      version: 6.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: recipes-db
  # See https://github.com/k8s-at-home/charts/blob/master/charts/stable/recipes/values.yaml
  values:
    image:
      repository: vabene1111/recipes
      tag: 1.1.4
    
    persistence:
      media:
        enabled: true
        existingClaim: recipes-media-pvc
      static:
        enabled: true
        existingClaim: recipes-static-pvc

    
    env:
      DEBUG: "0"
      ALLOWED_HOSTS: "*"
      #SECRET_KEY: set in secret
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      DB_OPTIONS: '{"sslmode":"require"}'
      POSTGRES_HOST: recipes-db-zalando-postgres-cluster-postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: set in secret
      TIMEZONE: Europe/Berlin
      REVERSE_PROXY_AUTH: 1
      HTTP_REMOTE_USER: HTTP_X_AUTHENTIK_USERNAME
      #SOCIAL_PROVIDERS: allauth.socialaccount.providers.nextcloud
      #SOCIALACCOUNT_PROVIDERS: '{"nextcloud":{"SERVER":"https://nextcloud.${CLUSTER_DOMAIN}"}}'
      # SOCIALACCOUNT_PROVIDERS: |
      #   {
      #       'openid': {
      #           'SERVERS': [
      #               { "id": 'authentik',
      #                 "name": 'authentik',
      #                 "openid_url": 'https://authentik.pub.${CLUSTER_DOMAIN}/application/o/tandoor-app/'
      #               },
      #           ]
      #       }
      #   }

    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "8000m"
        hosts:
        - host: recipes.pub.${CLUSTER_DOMAIN}
          paths:
          - path: /
            # Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
        - host: recipes.home.${CLUSTER_DOMAIN}
          paths:
          - path: /
            # Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
        tls:
        - hosts:
          - recipes.pub.${CLUSTER_DOMAIN}
          - recipes.home.${CLUSTER_DOMAIN}

  valuesFrom:
  - kind: Secret
    name: "recipes-helm-values"
    valuesKey: recipes.yaml
    optional: false
