apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    nextcloud.yaml: ENC[AES256_GCM,data:HVHSxZg4sIVo1wNvhnsuA6szR2tl3GkA9KAO+r5UCkem1pLItC4UoulNKqRPMfCIyd3iRtqPiEZ/nOp1iYCnUJserWxYDfNHCS5rSf3LWFI+Zn40lF6lLR9SrqjnPq0TboCG54D7thephfby9byLiuhIS7j2zQ5UP30bI18wimvICg9DXCFe,iv:WFi4+0k9z6ryKJKIX3EEicILCIFRBCaRZBVUYsKgIT8=,tag:iHPYKx9obV9/4EDzLTsY8Q==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:2HuZjCQxLziiDT6VXKm+F0e3ZIC22hlaGKzd8FYH0YSCbiV181zGwo/lRfd1Y02xtC/MNT3fJZabkjDxzsmhzbO/9xmZ4onPXqnVivvb31wEqTffhvVKts96h4pQosw/IiEXF4bk7TeoMurTKnarkw==,iv:f9OEI1Em1cj66me2wnqtdYiaR4AJXr4aKWODfdDM/+8=,tag:b0XyHJyNy4l+rZIlGATRXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-31T02:42:05Z'
    mac: ENC[AES256_GCM,data:tbpwXP31W+C0xR4p0U4zvfSqNQNCc7Un5hiP7i0UIZvHQcnuehaGHPZCnYgdLL8w+OhA49w/4sIOz7VqFfkTSx66BGbC7bqHGmZkIFd6hVFzlhTiwfguou3yh1PuNLGV8TdFb4pp03nihYAzyyMKwCUCIuKepZr/98i47S8DCbw=,iv:TEhgC3BQm5qpKp7ZZzAMzwqSfet7IlEUxMuJMrtUZjY=,tag:Fz8RbVrMQBgA9HZWOwOpNA==,type:str]
    pgp:
    -   created_at: '2021-02-06T22:26:03Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
        fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.6.1
