apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    nextcloud.yaml: ENC[AES256_GCM,data:ip/Um6sGcrDkjk2o5yVwLp9PEzPv1XLGmbi1txAbWiGMnUCYE0rjtG6dhqWNoDMras/KM0gKHdvpuV7sdeZjTMcUMdc1XaaoXkCPse6PeROUjSEOOBscu403GSHyYUWopERdJBCSWTCPyKHOqGvTguGhmYZcGlYOtxopLSFauN9pUh056u+lhm/XE0tXYxdwVfnQv3c/VNuiwoUzwVlpXuaqK9o5ImTgKwqnAUH1BrEV265xf6okyfu/ptYNfO/WDJiY7xceP2YClHGpgWAu5Ts=,iv:jPM2qBTZl+OErtAsPq2M7LK4mlPDzRpg8AUMAIRCYCY=,tag:uZqk8AAz4ux0wVSeK+LLHw==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:2HuZjCQxLziiDT6VXKm+F0e3ZIC22hlaGKzd8FYH0YSCbiV181zGwo/lRfd1Y02xtC/MNT3fJZabkjDxzsmhzbO/9xmZ4onPXqnVivvb31wEqTffhvVKts96h4pQosw/IiEXF4bk7TeoMurTKnarkw==,iv:f9OEI1Em1cj66me2wnqtdYiaR4AJXr4aKWODfdDM/+8=,tag:b0XyHJyNy4l+rZIlGATRXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-19T10:57:01Z"
    mac: ENC[AES256_GCM,data:+F0l8omCXTJVPNJ7uJkpFaOtR9uIqztnWuWwn/jp7yFjdVW5S2aqd7eqWKtSkfUkxDtU8DE97py4AE2IpUZKRYDSGaR1xMH8QlwOdoZZ2lbN7YP8A0wQh3Rx0RhRaJ2KNu1B6zqbo6uMC2U7w3Go/hr6F216PR3ScQ9VcrDOZaw=,iv:UZIwp1NCTjcg6jPCNKuUmS226mVN5V7YY6Jz5qxBzJU=,tag:w7o81eAAF8xJZ2iRm0PGog==,type:str]
    pgp:
        - created_at: "2021-02-06T22:26:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
