apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-helm-values
    #Password generate with https://generate.plus/en/base64
stringData:
    nextcloud.yaml: ENC[AES256_GCM,data:WjD0vQVvShqOarzsPlmBfqI9FK3Lim4Wmqr8nCt8rNeJtqXLauUqY+UUa2ePVuKCduotOYMMKiwUEbqf1kSzifAbtbbmev9LWfOKL6CaUVAx/5xPripHWTzy7kBzpdcuHk7pTLSIhNEMgP72O/iqkQpBJ1eH88MVB+LicFvGO3z+sGFT79I/0J8gmcK9iBSERMabjdK4M6bg52e9ctuJCoBiuWG3el7q3UrdZ+XMG6fHSKEziOPXW6GSKqvNbEiG6bNUlgb7+/dBD2qKU8AqrtXaSqQgi38OIpP6rKY59Q==,iv:Hzj8WE/ote9+GnCQ/mqdx8SuNHge/R9in0LOYrZUKKI=,tag:W2EN9TIilPoqXbuZqXhMpw==,type:str]
    postgres.yaml: ENC[AES256_GCM,data:2HuZjCQxLziiDT6VXKm+F0e3ZIC22hlaGKzd8FYH0YSCbiV181zGwo/lRfd1Y02xtC/MNT3fJZabkjDxzsmhzbO/9xmZ4onPXqnVivvb31wEqTffhvVKts96h4pQosw/IiEXF4bk7TeoMurTKnarkw==,iv:f9OEI1Em1cj66me2wnqtdYiaR4AJXr4aKWODfdDM/+8=,tag:b0XyHJyNy4l+rZIlGATRXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-11T19:14:09Z"
    mac: ENC[AES256_GCM,data:Y6OWSq2C6X+yQFySney2G/yN9bDQxMsJ/ChwnWMbB3StAtdMS0fIdQJ8fzfxJHTvBmbjcZ0HWf+AKwhcGrji+mzSmAPWxB7cPx78ZJiz+mFwYP4A7n+wu1B5sTcpE3PHPfnUD9pEUg+ka0rKWqNzUoomDi2Hi9c1cKrjmhBQdkc=,iv:yOMcP9HYXy2HsOJDYI69YsR+YxWQPFL/MaatvPpXb0o=,tag:lPrbjd3tyiM6zzcx3PE3CQ==,type:str]
    pgp:
        - created_at: "2021-02-06T22:26:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2CuQNd5ml+/AQ/9GHzYbKml+FrvNKkmUiAzL874+hqzASaUtxzVvQBjhHCx
            g9/cQ5rhHx1vbkrTPALAIxJyvZinZE/H4MFE039X0gH5eIzS3qNCcLFczBw5QGYL
            vkvEmCRn5pF+JxSiQXUw5ipYF9AWLITkb2ew/l6IMkXWcwQaDbERrBvlI2Lr1Mix
            Rc0X/jTEUwHDhbWFKXQ9fNwoW/rNqmiyUeHPV7i/XRI/RZgcTK1kofN7wS5cy6wF
            0uKBXdGrM6/U21iGFxc7S0YNYDgZwwW4FuEVbMs7H+TxK9pck9oxXws0myAdkMKW
            MhJUMyWBUM58PGw98sNEllOMq2MCkKr5fNjd9uDE9CQJmPbA+OvqhX1NyN7tE0A6
            /u0O5OZPh9PFaYLTrTQxZJuhDoE75vjWfSB1F8FXw9DMFl8a4VkZHQQXOynVPMwN
            krUZ8O1xoJ7YS6TaIdDMVRBRSoKAYbCBMEBRIqfMZsmnU316NW10f3I7zyiu8Zhx
            q+8Oh6ovVWy8a/DciLdJJjkKze28eYLRcAgFquKNtgiEOR6nA0bVA0yz6aWGFbHk
            gb0AHRym9WwrvI4005mIF4u1QsVReEQmv8dLwgOV3SiUDOhaMJt27XZ/c3ayWgHP
            OLV5izVSeeMDbEJMPpbVkHXzOd4PM02MKCrq+JVuQ4NEb4yoe1gu3XKhKNbi+IrS
            XAGY3d/+ImT7SBPzs8yKGZ8MnpoMTK4utFKvFJum+bXb9FMAffG7hGnoRt+5xfFe
            mIM6NpEKL5aW3jSdkqjKXlIr0ljnBb5wo+XUCl0QK5LX2VPBeHInYFaEszSP
            =Ts27
            -----END PGP MESSAGE-----
          fp: E61087FD0DC8B3AA734061498564C79FC27F08E2
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
