apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: esphome
      version: 8.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  # See https://github.com/k8s-at-home/charts/blob/master/charts/esphome/values.yaml
  values:
    image:
      repository: ghcr.io/esphome/esphome
      tag: 2021.8.2
    
    persistence:
      config:
        enabled: true
        existingClaim: esphome-pvc

    podAnnotations:
      k8s.v1.cni.cncf.io/networks: |
        [{
          "name":"macvlan-static",
          "namespace": "kube-system",
          "ips": ["${CLUSTER_EXTERNAL_SUBNET_PREFIX}.${CLUSTER_MACVLAN_ESPHOME}"]
        }]

    ingress:
      main:
        enabled: true
        hosts:
        - host: esphome.pub.${CLUSTER_DOMAIN}
          paths:
          - path: /
            # Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
        - host: esphome.home.${CLUSTER_DOMAIN}
          paths:
          - path: /
            # Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
        tls:
        - hosts:
          - esphome.pub.${CLUSTER_DOMAIN}
          - esphome.home.${CLUSTER_DOMAIN}

    addons:
      codeserver:
        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: 3.11.1
        enabled: true
        volumeMounts:
        - name: config
          mountPath: /config
        ingress:
          enabled: true
          hosts:
          - host: esphome-editor.home.${CLUSTER_DOMAIN}
            paths:
            - path: /
              pathType: Prefix
          - host: esphome-editor.pub.${CLUSTER_DOMAIN}
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - esphome-editor.home.${CLUSTER_DOMAIN}
            - esphome-editor.pub.${CLUSTER_DOMAIN}
