apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-csi-rbd
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=he
      chart: ceph-csi-rbd
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: flux-system
      interval: 5m
  #See https://github.com/ceph/ceph-csi/blob/devel/charts/ceph-csi-cephfs/values.yaml
  values:
    csiConfig:
    - clusterID: "84675d40-a0d9-11eb-b978-dbc90369c7ea" #just a UUID
      monitors:
      - 192.168.2.129:6789
      - 192.168.2.170:6789
      - 192.168.4.13:6789