apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-music-vpn
spec:
  storageClassName: nfs-music-vpn
  capacity:
    storage: 18T
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nas.home.angelnu.com
    path: "${NFS_MUSIC}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-music
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-music-vpn
  volumeName: nfs-music-vpn
  resources:
    requests:
      storage: 10T