apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forecastle 
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://stakater.github.io/stakater-charts
      chart: forecastle 
      version: v1.0.64
      sourceRef:
        kind: HelmRepository
        name: forecastle 
        namespace: flux-system
      interval: 5m
  # See https://github.com/stakater/Forecastle/blob/master/deployments/kubernetes/chart/forecastle/values.yaml
  values:
    forecastle:
      config:
        title: "${CLUSTER_DOMAIN} applications"
        namespaceSelector:
          any: true

      ingress:
        enabled: true
        hosts:
        - host: forecastle.pub.${CLUSTER_DOMAIN}
          paths:
          - /
        - host: forecastle.home.${CLUSTER_DOMAIN}
          paths:
          - /
        tls:
        - hosts:
          - forecastle.pub.${CLUSTER_DOMAIN}
          - forecastle.home.${CLUSTER_DOMAIN}